### ISSUE TITLE
is this supported for ROG Strix G712LU Windows 11 64bit?

### ISSUE THREAD

**Issue by HarukaRepo** [Tejaromalius/Vasus#1]
![image](https://github.com/user-attachments/assets/3925629a-2fab-41ca-a42e-41fd610dfeb3)

**Comment by Tejaromalius** [comment]
Unfortunately Vasus utilizes Asusctl which only works on Linux machines. So far no APIs or tools have been found to change ROG devices' keyboard color for windows. As soon as a good solution is found, extension gets updated :+1:
